// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBQNoqysC1n5cyvE6oIwBNOTKA7Ud_BcXY',
    appId: '1:413289618323:web:fe3780b215cd498d702666',
    messagingSenderId: '413289618323',
    projectId: 'fir-series-37e9c',
    authDomain: 'fir-series-37e9c.firebaseapp.com',
    storageBucket: 'fir-series-37e9c.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAmVi378AGYC0HJbNowxg1oBXouubhR2fk',
    appId: '1:146885914985:android:88b13019dd571577d70df8',
    messagingSenderId: '146885914985',
    projectId: 'sai-cabz-driver-app',
    storageBucket: 'sai-cabz-driver-app.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBm1KE3QI6ya86rAl-IlPIep4fzXCuAlJY',
    appId: '1:413289618323:ios:27c8bd2a790ef640702666',
    messagingSenderId: '413289618323',
    projectId: 'fir-series-37e9c',
    storageBucket: 'fir-series-37e9c.firebasestorage.app',
    iosBundleId: 'com.example.saiCabzDriverApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBm1KE3QI6ya86rAl-IlPIep4fzXCuAlJY',
    appId: '1:413289618323:ios:27c8bd2a790ef640702666',
    messagingSenderId: '413289618323',
    projectId: 'fir-series-37e9c',
    storageBucket: 'fir-series-37e9c.firebasestorage.app',
    iosBundleId: 'com.example.saiCabzDriverApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDPBRePcwAITeoBdxMuN7jrTPDP8bvMrhE',
    appId: '1:413289618323:web:511e1e5e0c5b6f6a702666',
    messagingSenderId: '413289618323',
    projectId: 'fir-series-37e9c',
    authDomain: 'fir-series-37e9c.firebaseapp.com',
    storageBucket: 'fir-series-37e9c.firebasestorage.app',
  );

}